language: node_js
node_js: 
  - 13

services:
  - docker

install:
  - echo 'nothing to install'

before_script:
  - echo 'no tests'

script:
  - docker build -t simple_node .
  - docker tag simple_node YOUR_DOCKER_HUB/simple_node:latest

after_sucess:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple_node